{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.services.gateway.adblock;

  blocklistScript = pkgs.writeShellScript "update-blocklists" ''
    set -euo pipefail

    WORKDIR=/var/lib/adblock
    BLOCKLIST=$WORKDIR/blocklist.txt
    KRESD_POLICY=$WORKDIR/policy.lua
    TEMP_LIST=$WORKDIR/blocklist.tmp

    mkdir -p $WORKDIR

    echo "Downloading blocklists..."
    > $TEMP_LIST

    ${lib.concatMapStringsSep "\n" (url: ''
      echo "  Fetching: ${url}"
      ${pkgs.curl}/bin/curl -sf "${url}" >> $TEMP_LIST || echo "Failed to fetch ${url}"
    '') cfg.blocklists}

    echo "Processing blocklists..."
    ${pkgs.gnugrep}/bin/grep -v '^#' $TEMP_LIST | \
      ${pkgs.gnugrep}/bin/grep -v '^$' | \
      ${pkgs.gawk}/bin/awk '{print $NF}' | \
      ${pkgs.gnused}/bin/sed 's/\r$//' | \
      ${pkgs.gnused}/bin/sed 's/^||//' | \
      ${pkgs.gnused}/bin/sed 's/\^$//' | \
      ${pkgs.gnused}/bin/sed 's/^|//' | \
      ${pkgs.gnused}/bin/sed 's/|$//' | \
      ${pkgs.gnugrep}/bin/grep -E '^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$' | \
      ${pkgs.coreutils}/bin/sort -u > $BLOCKLIST

    ${lib.optionalString (cfg.whitelist != [ ]) ''
      echo "Applying whitelist..."
      WHITELIST_TEMP=$WORKDIR/whitelist.tmp
      cat > $WHITELIST_TEMP <<EOF
      ${lib.concatStringsSep "\n" cfg.whitelist}
      EOF
      ${pkgs.gnugrep}/bin/grep -vFf $WHITELIST_TEMP $BLOCKLIST > $BLOCKLIST.filtered || true
      mv $BLOCKLIST.filtered $BLOCKLIST
      rm $WHITELIST_TEMP
    ''}

    ${lib.optionalString (cfg.blacklist != [ ]) ''
      echo "Applying blacklist..."
      cat >> $BLOCKLIST <<EOF
      ${lib.concatStringsSep "\n" cfg.blacklist}
      EOF
    ''}

    DOMAIN_COUNT=$(${pkgs.coreutils}/bin/wc -l < $BLOCKLIST)
    echo "Total domains blocked: $DOMAIN_COUNT"

    echo "Generating kresd policy..."
    cat > $KRESD_POLICY <<'EOF'
    -- Ad-blocking policy generated by adblock.nix
    -- Total blocked domains: DOMAIN_COUNT_PLACEHOLDER

    local blocklist_file = '/var/lib/adblock/blocklist.txt'
    local blocked_domains = {}

    -- Load blocklist from file
    local function load_blocklist()
      local file = io.open(blocklist_file, 'r')
      if not file then
        print('Warning: Could not open blocklist file')
        return
      end
      
      local count = 0
      for line in file:lines() do
        blocked_domains[line:lower()] = true
        count = count + 1
      end
      file:close()
      print('Loaded ' .. count .. ' blocked domains')
    end

    load_blocklist()

    policy.add(function(req, qry)
      local qname = kres.dname2str(qry:name()):lower()
      if qname:sub(-1) == "." then
        qname = qname:sub(1, -2)
      end
      
      -- Check exact match
      if blocked_domains[qname] then
        return policy.DENY
      end
      
      -- Check parent domains (for wildcard blocking)
      local labels = {}
      for label in qname:gmatch("[^.]+") do
        table.insert(labels, label)
      end
      
      for i = 2, #labels do
        local parent = table.concat(labels, ".", i)
        if blocked_domains[parent] then
          return policy.DENY
        end
      end
      
      return policy.PASS
    end)
    EOF

    ${pkgs.gnused}/bin/sed "s/DOMAIN_COUNT_PLACEHOLDER/$DOMAIN_COUNT/" -i $KRESD_POLICY

    echo "Blocklist update complete: $DOMAIN_COUNT domains blocked"

    # Signal kresd to reload
    ${pkgs.systemd}/bin/systemctl reload kresd@1.service || true
  '';

in
{
  options.services.gateway.adblock = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable DNS-based ad-blocking for LAN clients";
    };

    blocklists = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
        "https://big.oisd.nl/domainswild"
        "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0"
      ];
      description = "List of blocklist URLs to download and process";
    };

    whitelist = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [
        "example.com"
        "analytics.company.com"
      ];
      description = "Domains to never block (overrides blocklists)";
    };

    blacklist = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [
        "extra-tracker.com"
        "malicious-site.net"
      ];
      description = "Additional domains to block (not in blocklists)";
    };

    updateInterval = lib.mkOption {
      type = lib.types.str;
      default = "daily";
      description = "How often to update blocklists (systemd.time format)";
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.services.adblock-update = {
      description = "Update DNS ad-blocking lists";
      after = [
        "network-online.target"
        "kresd@1.service"
      ];
      wants = [
        "network-online.target"
        "kresd@1.service"
      ];
      serviceConfig = {
        Type = "oneshot";
        User = "adblock";
        Group = "adblock";
        ExecStart = blocklistScript;
        StateDirectory = "adblock";
        CacheDirectory = "adblock";
      };
      postStop = ''
        chmod 644 /var/lib/adblock/blocklist.txt
        chmod 644 /var/lib/adblock/policy.lua
      '';
    };

    systemd.timers.adblock-update = {
      description = "Update DNS ad-blocking lists timer";
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnBootSec = "5min";
        OnUnitActiveSec = cfg.updateInterval;
        Persistent = true;
      };
    };

    systemd.services."kresd@" = {
      serviceConfig = {
        ExecReload = lib.mkForce "${pkgs.coreutils}/bin/kill -SIGHUP $MAINPID";
      };
    };

    users.users.adblock = {
      isSystemUser = true;
      group = "adblock";
    };

    users.groups.adblock = { };

    services.kresd.instances = lib.mkDefault 1;
  };
}
