{ lib, pkgs }:

let
  inherit (lib)
    concatStringsSep
    optionalString
    mapAttrsToList
    ;

in {
  generateConfig = cfg:
    let
      # Backend director for origin servers
      originDirectors = concatStringsSep "\n\n" (map (origin: ''
        backend ${origin.name} {
          .host = "${origin.host}";
          .port = "${toString origin.port}";
          ${optionalString origin.tls ".first_byte_timeout = 60s;"}
          ${optionalString origin.tls ".connect_timeout = 5s;"}
          .max_connections = 100;
          .probe = {
            .url = "${if origin.tls then "https" else "http"}://${origin.host}:${toString origin.port}${origin.healthCheck.path}";
            .timeout = ${origin.healthCheck.timeout};
            .interval = ${origin.healthCheck.interval};
            .expected_response = ${toString origin.healthCheck.expectedStatus};
          };
        }
      '') cfg.origins);

      # Cache rule VCL
      cacheRules = concatStringsSep "\n    " (map (rule: ''
        if (req.url ~ "^${rule.path}$") {
          set beresp.ttl = std.duration("${rule.ttl}", 0s);
          set beresp.grace = 1h;
          ${optionalString (!rule.compression) "unset beresp.do_gzip;"}
          ${optionalString (!rule.cacheByQuery) "set req.hash_ignore_busy = true;"}
          ${optionalString (rule.vary != []) "set beresp.http.Vary = \"${concatStringsSep ", " rule.vary}\";"}
          ${optionalString rule.bypass "return (pass);"}
        }
      '') cfg.caching.rules);

      # Security headers VCL
      securityHeaders = ''
        # Security headers
        set resp.http.X-Frame-Options = "DENY";
        set resp.http.X-Content-Type-Options = "nosniff";
        set resp.http.X-XSS-Protection = "1; mode=block";
        set resp.http.Strict-Transport-Security = "max-age=31536000; includeSubDomains";
        set resp.http.Referrer-Policy = "strict-origin-when-cross-origin";
        
        # CDN-specific headers
        set resp.http.X-Cache-Status = obj.hits;
        set resp.http.X-Cache-TTL = beresp.ttl;
        set resp.http.X-Edge-Node = server.identity;
        set resp.http.X-Request-ID = req.xid;
      '';

      # Geographic VCL
      geographicRules = optionalString (cfg.security.geoBlock.allow != [] || cfg.security.geoBlock.deny != []) ''
        # Geographic filtering
        if (client.ip ~ geoip) {
          ${optionalString (cfg.security.geoBlock.allow != []) ''
          if (client.geoip.country_code !~ "^(${concatStringsSep "|" cfg.security.geoBlock.allow})$") {
            return (synth(403, "Access denied from your location"));
          }
          ''}
          
          ${optionalString (cfg.security.geoBlock.deny != []) ''
          if (client.geoip.country_code ~ "^(${concatStringsSep "|" cfg.security.geoBlock.deny})$") {
            return (synth(403, "Access denied from your location"));
          }
          ''}
        }
      '';

      # Compression VCL
      compressionRules = ''
        # Compression configuration
        if (beresp.http.content-type ~ "text/(html|css|javascript|plain|xml)" || 
            beresp.http.content-type ~ "application/(javascript|json|xml)" ||
            beresp.http.content-type ~ "font/") {
          set beresp.do_gzip = ${if cfg.optimization.compression.gzip then "true" else "false"};
          set beresp.do_gzip = ${if cfg.optimization.compression.brotli then "true" else "false"};
        }
      '';

      # Image optimization VCL
      imageOptimization = optionalString cfg.optimization.imageOptimization ''
        # Image optimization
        if (req.url ~ "\.(jpg|jpeg|png|gif|webp)$") {
          # Add WebP support
          if (req.http.Accept ~ "webp") {
            set req.url = regsub(req.url, "\.(jpg|jpeg|png)$", ".webp");
          }
          
          # Longer cache times for images
          set beresp.ttl = 30d;
          set beresp.grace = 7d;
        }
      '';

      # API caching rules
      apiRules = optionalString cfg.api.enable ''
        # API endpoints
        if (req.url ~ "^/api/") {
          # Don't cache API POST/PUT/DELETE requests
          if (req.method !~ "GET|HEAD") {
            return (pass);
          }
          
          # Short TTL for API responses
          set beresp.ttl = 5m;
          set beresp.grace = 30s;
        }
      '';

      # Mobile and device optimization
      deviceOptimization = ''
        # Device detection and optimization
        if (req.http.User-Agent ~ "Mobile|Android|iPhone") {
          set req.http.X-Device-Type = "mobile";
          set beresp.ttl = beresp.ttl * 0.8; # Shorter TTL for mobile
        } else {
          set req.http.X-Device-Type = "desktop";
        }
      '';

    in ''
      # Varnish Configuration for CDN: ${cfg.domain}
      # Generated by NixOS Gateway Framework
      
      vcl 4.1;
      
      # Import needed modules
      import std;
      import directors;
      import cookie;
      import header;
      import xkey;
      import geoip;
      
      # Backend directors
      ${originDirectors}
      
      # Director for load balancing
      sub vcl_init {
        new origin_director = directors.round_robin();
        ${concatStringsSep "\n    " (map (origin: ''
        origin_director.add_backend(${origin.name});'') cfg.origins)}
      }
      
      # Main request handling
      sub vcl_recv {
        # Set default backend
        set req.backend_hint = origin_director.backend();
        
        # Handle health checks
        if (req.method == "PURGE") {
          if (client.ip ~ purge) {
            return (purge);
          } else {
            return (synth(405, "Method not allowed"));
          }
        }
        
        # Handle BAN requests
        if (req.method == "BAN") {
          if (client.ip ~ ban) {
            ban("obj.http.X-Host ~ " + req.http.X-Host + " && obj.http.X-URL ~ " + req.http.X-URL);
            return (synth(200, "Banned"));
          } else {
            return (synth(403, "Forbidden"));
          }
        }
        
        # Normalize request method
        if (req.method !~ "GET|HEAD|PUT|POST|TRACE|OPTIONS|PATCH|DELETE|PURGE|BAN") {
          return (pipe);
        }
        
        # Normalize query parameters for cache key
        ${optionalString (!cfg.caching.cacheByQuery) ''
        if (req.url ~ "\?") {
          set req.url = regsub(req.url, "\?.*$", "");
        }
        ''}
        
        # Handle static files with long cache
        if (req.url ~ "\.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$") {
          set req.http.Cache-Control = "public, max-age=31536000";
        }
        
        # Pass through certain requests
        if (req.url ~ "^/(admin|api|health)") {
          return (pass);
        }
        
        # Apply geographic rules
        ${geographicRules}
        
        # Device optimization
        ${deviceOptimization}
        
        # Store original host and URL for ban handling
        set req.http.X-Host = req.http.host;
        set req.http.X-URL = req.url;
      }
      
      # Backend response handling
      sub vcl_backend_response {
        # Set default TTL
        set beresp.ttl = std.duration("${cfg.caching.defaultTtl}", 0s);
        set beresp.grace = std.duration("1h", 0s);
        set beresp.keep = std.duration("1h", 0s);
        
        # Don't cache error responses
        if (beresp.status >= 500) {
          set beresp.ttl = 10s;
          return (deliver);
        }
        
        # Don't cache authentication/authorization pages
        if (beresp.http.Set-Cookie || beresp.http.Authorization) {
          set beresp.uncacheable = true;
          return (deliver);
        }
        
        # Apply cache rules
        ${cacheRules}
        
        # Apply compression rules
        ${compressionRules}
        
        # Apply image optimization
        ${imageOptimization}
        
        # Apply API rules
        ${apiRules}
        
        # Enforce max TTL
        if (beresp.ttl > std.duration("${cfg.caching.maxTtl}", 0s)) {
          set beresp.ttl = std.duration("${cfg.caching.maxTtl}", 0s);
        }
        
        # Enforce min TTL
        if (beresp.ttl < std.duration("${cfg.caching.minTtl}", 0s)) {
          set beresp.ttl = std.duration("${cfg.caching.minTtl}", 0s);
        }
      }
      
      # Deliver response to client
      sub vcl_deliver {
        # Add security headers
        ${securityHeaders}
        
        # Add debugging headers
        if (obj.hits > 0) {
          set resp.http.X-Cache = "HIT";
          set resp.http.X-Cache-Hits = obj.hits;
        } else {
          set resp.http.X-Cache = "MISS";
        }
        
        # Add timing information
        set resp.http.X-Response-Time = time.elapsed;
        set resp.http.X-TTL = resp.ttl;
        
        # Remove internal headers
        unset resp.http.X-Varnish;
        unset resp.http.Via;
        unset resp.http.Server;
      }
      
      # Error handling
      sub vcl_synth {
        if (resp.status == 301 || resp.status == 302) {
          set resp.http.Location = resp.reason;
          set resp.reason = "Moved";
          return (deliver);
        }
        
        set resp.http.Content-Type = "text/html; charset=utf-8";
        set resp.http.Retry-After = "5";
        
        synthetic(<?
          <!DOCTYPE html>
          <html>
          <head>
            <title>'' + resp.status + '' '' + resp.reason + ''</title>
            <style>
              body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
              h1 { color: #e74c3c; }
            </style>
          </head>
          <body>
            <h1>'' + resp.status + '' '' + resp.reason + ''</h1>
            <p>CDN Edge Node Error</p>
            <p>Request ID: '' + req.xid + ''</p>
          </body>
          </html>
        ?>);
        return (deliver);
      }
      
      # Health check endpoint
      sub vcl_recv {
        if (req.url == "/health") {
          return (synth(200, "OK"));
        }
      }
      
      # ACL definitions
      acl purge {
        "127.0.0.1";
        "::1";
      }
      
      acl ban {
        "127.0.0.1";
        "::1";
      }
      
      # GeoIP database configuration
      sub vcl_init {
        # This would typically load a GeoIP database
        # geoip.load_database("/etc/varnish/GeoIP.dat");
      }
    '';

  # Generate VCL snippet for specific cache rules
  generateCacheRuleVCL = rule: ''
    if (req.url ~ "^${rule.path}$") {
      set beresp.ttl = std.duration("${rule.ttl}", 0s);
      ${optionalString (!rule.compression "unset beresp.do_gzip;")}
      ${optionalString (rule.vary != [] "set beresp.http.Vary = \"${concatStringsSep ", " rule.vary}\";")}
      ${optionalString rule.bypass "return (pass);"}
    }
  '';

  # Generate configuration for edge node specific optimizations
  generateEdgeNodeVCL = nodeName: node: ''
    # Edge node specific configuration for ${nodeName}
    sub vcl_recv {
      # Add edge node identification
      set req.http.X-Edge-Node = "${nodeName}";
      set req.http.X-Region = "${node.region}";
      set req.http.X-Location = "${node.location}";
      
      # Edge node specific routing based on capacity
      if (obj.hits > ${toString (node.capacity * 10)}) {
        # High traffic - route to next available edge
        return (restart);
      }
    }
  '';
}
