use std::env;
use std::fs;
use std::net::Ipv4Addr;
use std::path::Path;

mod config;

use config::GatewayConfig;

fn main() {
    let args: Vec<String> = env::args().collect();

    let config_path = args.iter()
        .position(|a| a == "--config")
        .and_then(|i| args.get(i + 1))
        .map(|s| s.as_str())
        .unwrap_or("/mnt/config/gateway.toml");

    let output_dir = args.iter()
        .position(|a| a == "--output")
        .and_then(|i| args.get(i + 1))
        .map(|s| s.as_str())
        .unwrap_or("/etc/gateway");

    let dry_run = args.iter().any(|a| a == "--dry-run");

    let config = match GatewayConfig::load(config_path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("gateway-setup: no config at {} ({}), using defaults", config_path, e);
            GatewayConfig::default()
        }
    };

    fs::create_dir_all(output_dir).expect("failed to create output dir");

    // Write all generated configs
    let generators: Vec<(&str, Box<dyn Fn(&GatewayConfig) -> String>)> = vec![
        ("hostname", Box::new(gen_hostname)),
        ("network", Box::new(gen_networkd)),
        ("nftables", Box::new(gen_nftables)),
        ("hosts", Box::new(gen_hosts)),
        ("resolv", Box::new(gen_resolv)),
        ("health", Box::new(gen_health_toml)),
    ];

    for (name, gen) in &generators {
        let content = gen(&config);
        let path = format!("{}/{}.conf", output_dir, name);

        if dry_run {
            println!("--- {} ---\n{}", path, content);
        } else {
            if let Err(e) = fs::write(&path, &content) {
                eprintln!("WARN: failed to write {}: {}", path, e);
            }
        }
    }

    // Generate hostapd configs for each WiFi radio
    if let Some(wifi) = &config.wifi {
        for (iface, radio) in wifi {
            let content = gen_hostapd(iface, radio);
            let path = format!("{}/hostapd-{}.conf", output_dir, iface);
            if dry_run {
                println!("--- {} ---\n{}", path, content);
            } else {
                let _ = fs::write(&path, &content);
            }
        }
    }

    if !dry_run {
        eprintln!("gateway-setup: config generated in {}", output_dir);
    }
}

fn gen_hostname(c: &GatewayConfig) -> String {
    c.hostname.clone().unwrap_or_else(|| "gw".to_string())
}

fn gen_networkd(c: &GatewayConfig) -> String {
    let wan = &c.network.wan_interface;
    let lan = &c.network.lan_interface;
    let gw_ip = &c.network.lan_ipv4;
    let prefix = c.network.lan_prefix_len;

    format!(
        "# Generated by gateway-setup — WAN
[Match]
Name={wan}

[Network]
DHCP=yes
IPv6AcceptRA=true

[DHCPv4]
RouteMetric=10

[DHCPv6]
RouteMetric=10

# Generated by gateway-setup — LAN
[Match]
Name={lan}

[Network]
Address={gw_ip}/{prefix}
ConfigureWithoutCarrier=true
IPv6AcceptRA=false
DHCPServer={dhcp}
{dhcp_config}
{ra_config}
",
        dhcp = if c.profile == "alix-networkd" { "true" } else { "false" },
        dhcp_config = if c.profile == "alix-networkd" {
            let pool = &c.dhcp;
            format!(
                "
[DHCPServer]
PoolOffset={offset}
PoolSize={size}
EmitDNS=true
DNS={gw_ip}
EmitRouter=true
Router={gw_ip}
EmitDomain=true
Domain={domain}
LeaseTime=86400
{static_leases}",
                offset = pool_offset(&pool.range_start, &c.network.lan_ipv4),
                size = pool_size(&pool.range_start, &pool.range_end),
                domain = c.domain(),
                static_leases = gen_networkd_static_leases(&c.hosts),
            )
        } else {
            String::new()
        },
        ra_config = if !c.network.ipv6_prefix.is_empty() {
            format!(
                "\nIPv6SendRA=true\n\
                 [IPv6Prefix]\n\
                 Prefix={}/64\n\
                 Assign=true",
                c.network.ipv6_prefix
            )
        } else {
            String::new()
        },
    )
}

fn gen_networkd_static_leases(hosts: &[config::Host]) -> String {
    hosts
        .iter()
        .filter(|h| !h.mac.is_empty() && !h.ip.is_empty())
        .map(|h| {
            format!(
                "\n[DHCPServerStaticLease]\nAddress={}\nMACAddress={}",
                h.ip, h.mac
            )
        })
        .collect()
}

fn gen_nftables(c: &GatewayConfig) -> String {
    let wan = &c.network.wan_interface;
    let lan = &c.network.lan_interface;

    format!(
        r#"#!/usr/sbin/nft -f
# Generated by gateway-setup

table inet filter {{
    chain forward {{
        type filter hook forward priority filter; policy accept;
        counter
    }}
}}

table inet mangle {{
    chain postrouting {{
        type route hook output priority mangle; policy accept;
        udp dport {{ 53, 123, 546, 547 }} ip dscp set cs6
        tcp dport {{ 53 }} ip dscp set cs6
    }}
}}

table ip nat {{
    chain postrouting {{
        type nat hook postrouting priority srcnat; policy accept;
        oifname "{wan}" masquerade
    }}
}}
"#,
        wan = wan,
        lan = lan,
    )
}

fn gen_hosts(c: &GatewayConfig) -> String {
    let domain = c.domain();
    let gw_ip = &c.network.lan_ipv4;
    let mut hosts = format!("127.0.0.1 localhost\n{} gw.{} gw\n", gw_ip, domain);

    for h in &c.hosts {
        if !h.ip.is_empty() && !h.name.is_empty() {
            hosts.push_str(&format!("{} {}.{} {}\n", h.ip, h.name, domain, h.name));
        }
    }

    hosts
}

fn gen_resolv(c: &GatewayConfig) -> String {
    let domain = c.domain();
    let gw_ip = &c.network.lan_ipv4;

    format!(
        "[Resolve]\nDNS={}\nDomains=~{}\n",
        if c.profile == "alix-dnsmasq" {
            gw_ip.clone()
        } else {
            "127.0.0.1".to_string()
        },
        domain,
    )
}

fn gen_health_toml(c: &GatewayConfig) -> String {
    format!(
        r#"check_interval_secs = 30
ping_target = "1.1.1.1"
wan_interface = "{}"
dns_test_domain = "one.one.one.one"
dns_server = "{}"
services = [
    "systemd-networkd.service",
    "sshd.service",
]
monitored_interfaces = [
    "{}",
    "{}",
]
"#,
        c.network.wan_interface,
        if c.profile == "alix-dnsmasq" {
            c.network.lan_ipv4.clone()
        } else {
            "127.0.0.1".to_string()
        },
        c.network.wan_interface,
        c.network.lan_interface,
    )
}

fn gen_hostapd(iface: &str, radio: &config::WifiRadio) -> String {
    format!(
        r#"interface={iface}
driver=nl80211
ssid={ssid}
channel={channel}
hw_mode={hw_mode}
ieee80211n=0
{hidden}{wpa_config}
"#,
        iface = iface,
        ssid = radio.ssid,
        channel = radio.channel,
        hw_mode = if radio.band == "5" { "a" } else { "g" },
        hidden = if radio.hidden { "ignore_broadcast_ssid=1\n" } else { "" },
        wpa_config = if let Some(pw) = &radio.passphrase {
            format!(
                "wpa=2\nwpa_passphrase={pw}\nwpa_key_mgmt=WPA-PSK\nrsn_pairwise=CCMP\n"
            )
        } else {
            String::new()
        },
    )
}

fn pool_offset(start: &str, subnet_gw: &str) -> u64 {
    start.split('.').last().and_then(|o| o.parse().ok()).unwrap_or(100)
}

fn pool_size(start: &str, end: &str) -> u64 {
    let s: u64 = start.split('.').last().and_then(|o| o.parse().ok()).unwrap_or(100);
    let e: u64 = end.split('.').last().and_then(|o| o.parse().ok()).unwrap_or(200);
    e.saturating_sub(s) + 1
}
