{ lib, pkgs, ... }:

let
  inherit (lib) mkOption types;

  # Define metric types
  metricType = types.submodule {
    options = {
      name = mkOption { type = types.str; };
      type = mkOption {
        type = types.enum [
          "counter"
          "gauge"
          "histogram"
        ];
      };
      description = mkOption {
        type = types.str;
        default = "";
      };
      labels = mkOption {
        type = types.listOf types.str;
        default = [ ];
      };
    };
  };

  # Helper to generate eBPF monitoring code
  mkMonitoringCode = metrics: ''
    #include <linux/bpf.h>
    #include <bpf/bpf_helpers.h>

    /*
     * eBPF Monitoring Program
     * Generated by NixOS Gateway Framework
     */

    ${lib.concatMapStringsSep "\n" (metric: ''
      struct {
          __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
          __uint(max_entries, 1024);
          __uint(type, ${
            if metric.type == "histogram" then "BPF_MAP_TYPE_PERCPU_ARRAY" else "BPF_MAP_TYPE_PERCPU_ARRAY"
          });
          __type(key, u32);
          __type(value, u64);
      } ${metric.name}_map SEC(".maps");
    '') metrics}

    SEC("xdp")
    int xdp_monitor_prog(struct xdp_md *ctx) {
        void *data_end = (void *)(long)ctx->data_end;
        void *data = (void *)(long)ctx->data;
        
        // Basic packet parsing
        struct ethhdr *eth = data;
        if (data + sizeof(*eth) > data_end)
            return XDP_PASS;

        struct iphdr *ip = data + sizeof(*eth);
        if (data + sizeof(*eth) + sizeof(*ip) > data_end)
            return XDP_PASS;
            
        // Update metrics
        ${lib.concatMapStringsSep "\n    " (metric: ''
          u32 key = 0; // Simplified key for now
          u64 *val = bpf_map_lookup_elem(&${metric.name}_map, &key);
          if (val) {
              __sync_fetch_and_add(val, 1);
          }
        '') metrics}

        return XDP_PASS;
    }

    char _license[] SEC("license") = "GPL";
  '';

  # Standard metrics included by default
  standardMetrics = [
    {
      name = "packets_total";
      type = "counter";
      description = "Total packets processed";
    }
    {
      name = "bytes_total";
      type = "counter";
      description = "Total bytes processed";
    }
    {
      name = "drops_total";
      type = "counter";
      description = "Total packets dropped";
    }
  ];

in
{
  inherit mkMonitoringCode standardMetrics;

  # Function to generate Prometheus exporter config for these metrics
  mkPrometheusConfig = metrics: {
    global = {
      scrape_interval = "15s";
    };
    scrape_configs = [
      {
        job_name = "ebpf_monitoring";
        static_configs = [
          { targets = [ "localhost:9091" ]; }
        ];
      }
    ];
  };
}
