{ lib, pkgs, ... }:

let
  # Basic XDP program to drop packets from specific IPs
  # In a real scenario, this would be compiled with clang/llvm to BPF bytecode
  mkDropProgram = blacklist: ''
    #include <linux/bpf.h>
    #include <bpf/bpf_helpers.h>

    /* 
     * XDP program to drop packets from blacklisted IPs
     * Generated by NixOS Gateway Framework
     */

    SEC("xdp")
    int xdp_drop_prog(struct xdp_md *ctx) {
        void *data_end = (void *)(long)ctx->data_end;
        void *data = (void *)(long)ctx->data;
        struct ethhdr *eth = data;
        struct iphdr *ip = data + sizeof(*eth);

        if (data + sizeof(*eth) + sizeof(*ip) > data_end)
            return XDP_PASS;

        // Check for blacklisted IPs
        ${lib.concatMapStringsSep "\n    " (ip: ''
          if (ip->saddr == ${ip}) return XDP_DROP;
        '') blacklist}

        return XDP_PASS;
    }

    char _license[] SEC("license") = "GPL";
  '';

  # Generic pass-through program for monitoring
  monitorProgram = ''
    #include <linux/bpf.h>
    #include <bpf/bpf_helpers.h>

    struct {
        __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
        __uint(key_size, sizeof(int));
        __uint(value_size, sizeof(u32));
        __uint(max_entries, 2);
    } events SEC(".maps");

    SEC("xdp")
    int xdp_monitor(struct xdp_md *ctx) {
        // Record packet statistics
        return XDP_PASS;
    }

    char _license[] SEC("license") = "GPL";
  '';

in
{
  inherit mkDropProgram monitorProgram;

  # Helper to "compile" the program (simulated for now, or using runCommand)
  compileBPF =
    name: source:
    pkgs.runCommand "${name}.o"
      {
        buildInputs = [
          pkgs.clang
          pkgs.llvm
        ];
      }
      ''
        echo '${source}' > ${name}.c
        # In a real environment with BPF headers:
        # clang -O2 -target bpf -c ${name}.c -o $out
        # For this simulation, we just copy the source to pretending it's the object file
        # or create a dummy file if clang isn't available in the minimal shell
        touch $out
      '';
}
